"""Error handling module."""
from flask import jsonify
import insta485


class InvalidUsage(Exception):
    """A class to handle exceptions generated by the app."""

    status_code = 400

    def __init__(self, message, status_code=None, payload=None):
        """Initialize invalid usage object."""
        Exception.__init__(self)
        self.message = message
        if status_code is not None:
            self.status_code = status_code
        self.payload = payload

    def to_dict(self):
        """Convert input to dict."""
        rv = dict(self.payload or ())
        rv['message'] = self.message
        if self.status_code is not None:
            rv['status_code'] = self.status_code
        return rv


@insta485.app.errorhandler(InvalidUsage)
def handle_invalid_usage(error):
    """Error handler."""
    response = jsonify(error.to_dict())
    response.status_code = error.status_code
    return response
